name = "Delta"
uuid = "9e3a83e1-479c-4d1c-ae0a-a5bbc61f1663"
license = "MIT"
authors = ["sole <sonosole@163.com>"]
version = "0.1.0"

[deps]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
julia = "1.0.0"
